# Dependencies
markdown:         kramdown
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Why &amp; How
tagline:          '崴&amp;灏'
description:      '以生之有涯随知之无涯，殆矣，然何为，为何为。'
url:              https://wanglongqi.github.io

author:
  name:           'WANG Longqi'
  url:            https://wanglongqi.github.io

paginate:         10

# Custom vars

github:
  repo:           https://github.com/wanglongqi
